project_id = "mxmarjrkwrqnhhipckzj"

[functions.fetch-ticker-data]
verify_jwt = false

[functions.generate-headline]
verify_jwt = false

[functions.send-newsletter-confirmation]
verify_jwt = false

[functions.send-weekly-newsletter]
verify_jwt = false

[functions.send-daily-newsletter]
verify_jwt = false

[functions.post-to-bluesky]
verify_jwt = false