project_id = "mxmarjrkwrqnhhipckzj"

[functions.fetch-ticker-data]
verify_jwt = false

[functions.generate-headline]
verify_jwt = false

[functions.send-newsletter-confirmation]
verify_jwt = false

[functions.send-weekly-newsletter]
verify_jwt = false

[functions.send-daily-newsletter]
verify_jwt = false

[functions.post-to-bluesky]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.test-balldontlie]
verify_jwt = false

[functions.fetch-football-stats]
verify_jwt = false

[functions.fetch-nba-stats]
verify_jwt = false

[functions.fetch-hollinger-stats]
verify_jwt = false
