project_id = "vdhbabgqozdemurgjusf"

[functions.fetch-nba-stats]
verify_jwt = false

[functions.fetch-football-stats]
verify_jwt = false

[functions.fetch-hollinger-stats]
verify_jwt = false

[functions.fetch-ticker-data]
verify_jwt = false

[functions.fetch-transfermarkt-data]
verify_jwt = false

[functions.send-newsletter-confirmation]
verify_jwt = false

[functions.send-daily-newsletter]
verify_jwt = false

[functions.send-weekly-newsletter]
verify_jwt = false

[functions.sync-live-matches]
verify_jwt = false

[functions.fetch-athlete-news]
verify_jwt = false

[functions.fetch-espn-player-stats]
verify_jwt = false

[functions.download-instagram]
verify_jwt = false

[functions.sync-match-schedule]
verify_jwt = false
